version: '3'

services:
  backend:
    build: ./python
    container_name: gen-text-backend
    networks:
      br0:
        ipv4_address: '10.0.3.90'
      environment:
        - TOKEN

networks:
  br0:
    external:
      name: br0
